/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2015-05-12 13:04:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>芒果搜索</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html;charset=UTF-8\" />\n");
      out.write("<script type='text/javascript'\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dwr/engine.js\"></script>\n");
      out.write("<script type='text/javascript'\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dwr/util.js\"></script>\n");
      out.write("<script type='text/javascript'\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/dwr/interface/searchService.js\"></script>\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\n");
      out.write("<meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\n");
      out.write("<meta http-equiv=\"description\" content=\"This is my page\">\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"./css/mango.css\" />\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"maindiv\" style=\"display:block\">\n");
      out.write("\t<div align=\"center\">\n");
      out.write("\t\t<div style=\"height: 150px\"></div>\n");
      out.write("\t\t<div >\n");
      out.write("\t\t\t<span class=\"hook\"></span> <img src=\"./image/MangoLogo.png\"/>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<input class=\"s_input\" type=\"text\" id=\"word\" value=\"\"\n");
      out.write("\t\t\t\t\t\tonclick=\"keyup()\" /> \n");
      out.write("\t\t\t<input class=\"submit s_btn\"type=\"submit\" value=\"GO\" id=\"sub\" />\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\t<div id=\"searchdiv\" style=\"display: none\">\n");
      out.write("\t\t<div style=\" background-color: #ffffff; width: 100%; height: 80px;  position: fixed; left: 0; top: 0; overflow: hidden\">\n");
      out.write("\t\t\t<table style=\"height: 55px\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td align=\"left\">\n");
      out.write("\t\t\t\t\t\t<div style=\"height: 5px\"></div>\n");
      out.write("\t\t\t\t\t\t<div class=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t<span class=\"hook\"></span> <img src=\"./image/MangoLogo.png\"\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 101px\" />\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div style=\"height: 20px\"></div>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t\t<td height=\"50\" align=\"center\"><input type=\"hidden\"\n");
      out.write("\t\t\t\t\t\tname=\"startindex\" id=\"startindex\" value=\"1\"> <input\n");
      out.write("\t\t\t\t\t\tclass=\"s_input\" type=\"text\" name=\"query\" id=\"query\" value=\"人民网\"\n");
      out.write("\t\t\t\t\t\tonkeyup=\"handlekey()\" /> <input class=\"submit s_btn\"\n");
      out.write("\t\t\t\t\t\ttype=\"submit\" name=\"submit\" value=\"GO\" id=\"submit\"\n");
      out.write("\t\t\t\t\t\tonclick=\"doSearch('')\" /></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div style=\"height: 100px\"></div>\n");
      out.write("\t\t<div id=\"result\"></div>\n");
      out.write("\n");
      out.write("\t\t<hr>\n");
      out.write("\n");
      out.write("\t\t<div id=\"paging\" class=\"pagination\"></div>\n");
      out.write("\t\t<div style=\"height: 120px\"></div>\n");
      out.write("\t\t<div class=\"footer\"\n");
      out.write("\t\t\tstyle=\"position: fixed; bottom: 0px; width: 100%; background-color: #ffffff\">\n");
      out.write("\t\t\t<div id=\"footer\" align=\"center\" style=\"background-color: #ffffff\">\n");
      out.write("\t\t\t\t<font size=\"3\"><a href=\"http://www.wyu.edu.cn/\"\n");
      out.write("\t\t\t\t\tclass=\"hover{color:#ff0000;}\">五邑大学</a>-<a\n");
      out.write("\t\t\t\t\thref=\"http://www.wyu.edu.cn/\">计算机学院</a></font>\n");
      out.write("\t\t\t\t<p id=\"copyright\">Copyright &copy; 2015|何嵩文|芒果搜索引擎</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\" src=\"./js/search.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
